---
title: "First meeting"
author: "Gustav Delius"
date: "10/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We had our first meeting by zoom at 2pm on Friday 9 October 2020. Everyone was
present and everyone briefly introduced themselves.

We agreed that for the rest of the autumn term we will meet weekly at 2pm on Tuesdays via zoom at <https://york-ac-uk.zoom.us/j/5277386983>.

During the first week everyone will concentrate on getting comfortable with R, RStudio, R Markdown, Git and GitHub. For this purpose I recommend to follow the lectures in the MOOC "[The Data Scientist's Toolbox](https://www.coursera.org/learn/data-scientists-tools)". From this we only need weeks 2 and 3 and the first section of week 4.

Before next meeting I would like everyone to create a repository for their final-year project on GitHub. 

As a GitHub challenge: try to edit this file to link your name below to your GitHub repository and then make a pull request. (You will have to figure out what that even means.)

-   [Gustav Delius](https://github.com/gustavdelius/fisheries-data-analysis)
-   [Chloe Hodson](https://github.com/ChloeH276/Third-Year-Project)
-   [Jacob Passfield](https://github.com/jacobpassfield/third-year-project)
-   [Maisie Beckett](https://github.com/maisiebeckett/3rd-year-project)
-   [Scott Connors](https://github.com/Scott-Connors/3rd-Year-Project)
-   Tallulah Coyte
-   Felix Carter (https://github.com/Felix-C577/Third-Year-Project)

## 15 October

Short meeting with everyone present. No one reports any difficulties with Git and GitHub. 

For next week I propose that everyone work through ["An introduction to basic fisheries analysis with R"](https://sfg-ucsb.github.io/fishery-manageR/). There you will learn a lot of skills necessary for
taking a first look at data. Please try to not only reproduce the analysis in that document, but
play around a bit, for example changing the way the data is plotted. This will prepare you for
when you get your own data set to visualise.

